version: '3'

services:
  web:
    build: .
    volumes:
      - "./app:/src/app"
    image: node:alpine
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MYSQL_DATABASE=nodejs-course
      - MYSQL_USER=node
      - MYSQL_PASSWORD=n0de-SC
    networks:
      default:
      internal:
  db:
    image: mariadb
    restart: always
    networks:
      internal:
    volumes:
      - .data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodejs-course
      - MYSQL_USER=node
      - MYSQL_PASSWORD=n0de-SC
      - MYSQL_ROOT_PASSWORD=n0de-SC
networks:
  default:
  internal:
    internal: true